apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servicename }}
  labels:
    app: {{ template "ordersdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    implementation: microprofile
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "ordersdb.fullname" . }}
    implementation: microprofile
