# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  #repository: registry.csplab.cloudns.cx/microprofile/orders-mp
  #repository: ibmcase/orders-mp
  repository: orders-mp
  tag: v1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

service:
  name: orders
  sqlservicename: mysqld-service
  type: ClusterIP
  servicePort: 9080
  servicePortHttps: 9443

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

sql:
  user: root
  password: password
  port: 3306

jwt:
  id: myMpJwt
  uri: https://auth-service:9443/oidc/endpoint/OP/jwk
  issuer: https://auth-service:9443/oidc/endpoint/OP

rabbitmq:
  mainPort: 5672
  managePort: 15672
