replicaCount: 1

image:
  repository: ibmcase/bluecompute-orders
  tag: 0.5.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  nodePort: 31384

ingress:
  enabled: false
  hostname: orders.bluecompute.com
  path: /micro/orders
  ibmCloud:
    redirectToHTTPS: false

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

mariadb:
  host: orders-mariadb-orders-mariadb
  port: 3306
  existingSecret:
  user: dbuser
  password: password
  database: ordersdb

# Used to check that MariaDB deployment is ready
mysql:
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent

hs256key:
  # If there is an existing secret with the key, provide it here
  secretName:
  secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

global:
  hs256key:
    secretName:

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi