{{ if and (or .Values.global.istio.enabled .Values.istio.enabled) .Values.istio.enableGateway }}
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: {{ template "orders.fullname" . }}-gateway
#spec:
#  selector:
#    app: {{ .Values.labels.app }}
#  servers:
#  - port:
#      number: {{ .Values.service.externalPort }}
#      name: http
#      protocol: HTTP
#    hosts:
#    - {{ template "orders.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
#    {{- range .Values.istio.hosts }}
#    - {{ . | title | quote }}
#    {{- end }}
#    tls:
#      httpsRedirect: {{ .Values.istio.httpsRedirect }}

#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: {{ template "orders.fullname" . }}-gateway
#spec:
#  selector:
#    istio: ingressgateway # use istio default controller
#  servers:
#  - port:
#      number: 80
#      name: http
#      protocol: HTTP
#    hosts:
#    - "*"
{{ end }}