{{- if and (not .Values.mariadb.existingSecret) .Values.mariadb.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-mariadb-secret
  labels:
    {{- include "orders.labels" . | indent 4 }}
type: Opaque
data:
  mariadb-password: "{{ .Values.mariadb.db.password | b64enc }}"
{{- end }}
