{{- if and (not .Values.mariadb.enabled) .Values.mariadb.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orders.fullname" . }}-mariadb-secret
  labels:
    {{- include "orders.labels" . | indent 4 }}
type: Opaque
data:
  mariadb-password: "{{ .Values.mariadb.db.password | b64enc }}"
{{- end }}