apiVersion: v1
entries:
  orders:
  - apiVersion: v1
    created: "2019-09-30T14:15:58.536085-05:00"
    description: BlueCompute Orders Microservice
    digest: f2a4a5fb4a001aca5a8d86dd293d3cbfa9af5d219cbc164289743a4e92cddb23
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-09-30T14:15:58.535126-05:00"
    description: BlueCompute Orders Microservice
    digest: c25abc811ea536f251ad8606aca2e1ebf95bd1d38d50e7a215daa2b99d6e79b7
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2019-09-30T14:15:58.532744-05:00"
    description: BlueCompute Orders Microservice
    digest: abac7c97d6b7818c17d14ece7b1f7fbd5ebba175de2422325a6d3aecd823f7ee
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.0.1.tgz
    version: 0.0.1
generated: "2019-09-30T14:15:58.531588-05:00"
